version: "3.9"

services:
  reverse-proxy:
    build:
      context: nginx
      dockerfile: dockerfile
    ports:
      - 80:80
    depends_on:
      - frontend

  frontend:
    build:
      context: frontend
      dockerfile: dockerfile
    depends_on:
      - backend
    ports:
      - 5000:5000

  backend:
    build:
      context: backend
      dockerfile: dockerfile
    ports:
      - 8000:8000

volumes:
  back-notused:
  db-data:
