version: "3.9"

services:
  reverse-proxy:
    image: 596051128564.dkr.ecr.ap-south-1.amazonaws.com/rl_portfolio_reverse_proxy:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      - frontend
    
  frontend:
    image: 596051128564.dkr.ecr.ap-south-1.amazonaws.com/rl_portfolio_frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/code
      
  backend:
    image: 596051128564.dkr.ecr.ap-south-1.amazonaws.com/rl_portfolio_backend:latest
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code

volumes:
  back-notused:
  db-data:
