version: "3.9"

services:
  web:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      PORT: 5000
    volumes:
      - .:/project/rl_portfolio/

