version: "3.9"

services:
  reverse-proxy:
    build:
      context: nginx
      dockerfile: dockerfile
    ports:
      - 80:80
    depends_on:
      - frontend

  frontend:
    build:
      context: frontend
      dockerfile: dockerfile
    depends_on:
      - backend
    ports:
      - 5000:5000
    volumes:
      - ./frontend/.env:/code/.env

  backend:
    build:
      context: backend
      dockerfile: dockerfile
    depends_on:
      - mysql
    ports:
      - 8000:8000
    volumes:
      - ./backend/.env:/code/.env

  mysql:
    image: mysql:8.0.27
    restart: always
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rl01111998
      MYSQL_DATABASE: database

volumes:
  back-notused:
  db-data:
