version: "3.9"

services:
  reverse-proxy:
    image: 596051128564.dkr.ecr.ap-south-1.amazonaws.com/rl_portfolio_reverse_proxy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    volumes:
      - ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt

  frontend:
    image: 596051128564.dkr.ecr.ap-south-1.amazonaws.com/rl_portfolio_frontend:latest
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend/.next:/code/.next

  backend:
    image: 596051128564.dkr.ecr.ap-south-1.amazonaws.com/rl_portfolio_backend:latest
    restart: always
    volumes:
      - ./backend/dist:/backend/dist

volumes:
  back-notused:
