version: "3.9"

services:
  reverse-proxy:
    image: 596051128564.dkr.ecr.ap-south-1.amazonaws.com/rl_portfolio_reverse_proxy:latest
    ports:
      - 80:80
    depends_on:
      - frontend

  frontend:
    image: 596051128564.dkr.ecr.ap-south-1.amazonaws.com/rl_portfolio_frontend:latest
    depends_on:
      - backend
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/code

  backend:
    image: 596051128564.dkr.ecr.ap-south-1.amazonaws.com/rl_portfolio_backend:latest
    depends_on:
      - mysql
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code

  mysql:
    image: mysql:8.0.27
    restart: always
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rl01111998
      MYSQL_DATABASE: database

volumes:
  back-notused:
  db-data:
