version: "3.9"

services:
  webserver:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path /var/www/certbot/ -d roysonlewis.com -d wwww.roysonlewis.com
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - webserver

  frontend:
    build:
      context: frontend
      dockerfile: dockerfile

volumes:
  back-notused:

