version: "3.9"

services:
  reverse-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: reverse-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - frontend
    links:
      - frontend
      - backend
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/code
    networks:
      - public
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/code
    networks:
      - public
      - private
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.27
    restart: always
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - private
    environment:
      MYSQL_ROOT_PASSWORD: rl01111998
      MYSQL_DATABASE: database

networks:
  public:
  private:

volumes:
  back-notused:
  db-data:
