version: "3.9"

services:
  reverse-proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    volumes:
      - ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt

  frontend:
    build:
      context: frontend
      dockerfile: dockerfile
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: dockerfile

volumes:
  back-notused:

