version: "3.9"

services:
  webserver:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
    depends_on:
      - webserver

  frontend:
    build:
      context: frontend
      dockerfile: dockerfile
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: dockerfile

volumes:
  back-notused:

