version: "3.9"

services:
  reverse-proxy:
    build:
      context: nginx
      dockerfile: dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    volumes:
      - ./nginx/configs:/etc/nginx/conf.d
      - ./nginx/certs/roysonlewis.com:/etc/ssl/certs/roysonlewis.com

  frontend:
    build:
      context: frontend
      dockerfile: dockerfile
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend/node_modules:/code/node_modules
      - ./frontend/.next:/code/.next
      
  backend:
    build:
      context: backend
      dockerfile: dockerfile
    restart: always

volumes:
  back-notused:
  db-data:
