name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Build and Push Docker Image
        run: |
          make build
          docker build -t my-app .
          docker tag backend:tagname lewisroysonj/portfolio:tagname
          docker push lewisroysonj/portfolio:tagname
          docker ps

      - name: execute remote ssh commands using password
        uses: ./
        env:
          TEST: "Test"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            echo "Testing $TEST"
  
