name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  AWS_ROLE: arn:aws:iam::596051128564:role/rl_portfolio_github_actions
  ECS_SERVICE: rl_portfolio
  ECS_CLUSTER: rl_portfolio
  ECS_TASK_DEFINITION: .github/workflows/task-definition.json

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
  
jobs:
  build:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-duration-seconds: 3000
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Images
        run: |
            make build-production
      
      - name: Tag Images
        run: |
            docker tag portfolio_backend:latest 596051128564.dkr.ecr.ap-south-1.amazonaws.com/rl_portfolio_backend:latest
            
      - name: Push Images
        run: |
            docker push 596051128564.dkr.ecr.ap-south-1.amazonaws.com/rl_portfolio_backend:latest
          
