name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Build and Push Docker Image
        run: |
          make build
          docker images
          echo "$secrets.DOCKER_PASSWORD" | docker login -u "lewisroysonj" --password-stdin
          docker tag portfolio_backend:latest lewisroysonj/portfolio:backend
          docker tag portfolio_frontend:latest lewisroysonj/portfolio:frontend
          docker tag mysql:8.0.27 lewisroysonj/portfolio:mysql
          docker push lewisroysonj/portfolio:frontend
          docker push lewisroysonj/portfolio:backend
          docker push lewisroysonj/portfolio:mysql

      - name: execute remote ssh commands using password
        uses: ./
        env:
          TEST: "Test"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            echo "Testing $TEST"
  
