name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECS_SERVICE: rl_portfolio
  ECS_CLUSTER: rl_portfolio
  ECS_TASK_DEFINITION: .github/workflows/task-definition.json
  
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          make build
          docker tag portfolio_frontend:latest lewisroysonj/portfolio:frontend
          docker tag portfolio_backend:latest lewisroysonj/portfolio:backend
          docker tag mysql:8.0.27 lewisroysonj/portfolio:mysql
          docker push lewisroysonj/portfolio:frontend
          docker push lewisroysonj/portfolio:backend
          docker push lewisroysonj/portfolio:mysql

      - name: Deploy to EC2
        uses: ./

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            echo "Testing $TEST"
  
