name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the Repository
        uses: actions/checkout@v3
      
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Build and Push Docker Images
        run: |
          make build
          docker tag portfolio_frontend:latest lewisroysonj/portfolio:frontend
          docker tag portfolio_backend:latest lewisroysonj/portfolio:backend
          docker tag mysql:8.0.27 lewisroysonj/portfolio:mysql
          docker push lewisroysonj/portfolio:frontend
          docker push lewisroysonj/portfolio:backend
          docker push lewisroysonj/portfolio:mysql
          
      - name: execute remote ssh commands using password
        uses: ./

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            echo "Testing $TEST"
  
