name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  AWS_ROLE: arn:aws:iam::596051128564:role/rl_portfolio_github_actions
  CONTAINER_REGISTRY_URL: 596051128564.dkr.ecr.ap-south-1.amazonaws.com
  AWS_S3_BUCKET_NAME: rl-portfolio
  AWS_EC2_PRIVATE_KEY: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
  AWS_EC2_HOSTNAME: ${{ secrets.AWS_EC2_HOSTNAME }}
  AWS_EC2_USERNAME: ${{ secrets.AWS_EC2_USERNAME }}

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
  
jobs:
  build:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-duration-seconds: 3000
          aws-region: ${{ env.AWS_REGION }}

      - name: Pass Secret Envs
        run: |
          echo DB_PASSWORD=${{ secrets.RL_PORTFOLIO_DB_PROD_PASSWORD }} >> ./backend/src/config/parameters/production.env

      - name: Build and Start Docker Containers
        run: |
          make build-production
          docker images
          make up-production
      
      - name: Run DB Migrations
        run: |
          make migration-run

      - name: Bundle Frontend Projects
        run: |
          make bundle-frontend

      - name: Push Bundled Project Folder to S3 Bucket
        run: |
          ls -a
          rsync -avz -e "ssh -i private_key" ./frontend/.next ${AWS_EC2_USERNAME}@${AWS_EC2_HOSTNAME}:~/frontend_bundle/.next

      - name: SSH into EC2 Instance and Run Deployment Script
        run: |
          echo "$AWS_EC2_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_EC2_USERNAME}@${AWS_EC2_HOSTNAME} '
            # Checkout project repo
            sudo rm -rf rl_portfolio &&
            git clone git@github.com:royson-lewis/rl_portfolio.git &&
            cd rl_portfolio &&
            git checkout main &&

            # Pass Secret Envs
            echo DB_PASSWORD=${{ secrets.RL_PORTFOLIO_DB_PROD_PASSWORD }} >> ./backend/src/config/parameters/production.env &&

            # Copy SSL certificates to project
            sudo cp -r /etc/ssl/roysonlewis.com ./nginx/certs/roysonlewis.com &&

            # Copy bundled project from s3 bucket and start the frontend website
            sudo cp -r ~/frontend_bundle/.next ./frontend/.next &&

            # Build and start docker containers
            make build-production &&
            make up-production &&

            # Start frontend website
            make serve-frontend &&

            # Configure startup service
            sudo rm /etc/systemd/system/startup.service && 
            sudo cp deployment/config/startup.service /etc/systemd/system/startup.service &&
            sudo systemctl daemon-reload &&
            sudo systemctl enable startup.service
          '
      